### ISSUE TITLE
Please, give me advice what to do in this case

### ISSUE THREAD

**Issue by SneKKaY** [Killface1980/DualSense4Rockstar#28] opened 2023-12-10 19:34 UTC
![photo_2023-12-10_22-32-59](https://github.com/Killface1980/DualSense4Rockstar/assets/120265382/c4d7e117-6a7f-44d7-9423-75d0c0c3c0b8)

**Comment by tikh-iv** [comment] 2024-04-02 09:25
Hello
Have you found any solution?

**Comment by SneKKaY** [comment] 2024-04-02 10:05
> Hello
> Have you found any solution? 

No, I gave up

**Comment by tikh-iv** [comment] 2024-04-02 14:11
> > Hello
> > Have you found any solution?
> 
> No, I gave up

I just found out
1) Use DualSenseX v2 (not v3 srteam version)
2) create `C:\temp\DualSenseX\DualSenseX_PortNumber.txt` with 
``` text
6969

```
3) Set up this file in Main page
4) Set up xbox emulation

After that it starts work

**Comment by Killface1980** [comment] 2024-06-22 23:08
Duplicate of #15

**Closed** 2024-11-15 20:39 UTC
Labels: bug, WIP, DSX Base
